### ISSUE TITLE
Kotlin Compiler

### ISSUE THREAD

**Issue by AGoh2019** [akamud/vscode-caniuse#22]
Issue Type: <b>Feature Request</b>

Can Microsoft develop a Kotlin compiler for VS Code.  

Extension version: 0.5.4
VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:08.962Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by akamud** [comment]
I'm sorry, this is not the right repo for this. You should try the vscode repo. Also, there are a few extensions on the marketplace that seem to support Kotlin for VSCode: https://marketplace.visualstudio.com/search?term=kotlin&target=VSCode&category=Programming%20Languages&sortBy=Relevance
