### ISSUE TITLE
Flexbox?

### ISSUE THREAD

**Issue by OscarGodson** [akamud/vscode-caniuse#6]
I was trying to see `display:flex` support but I'm not sure what to highlight. I just get entry not found highlighting `flex`. and `display` says everything supports it.

**Comment by OscarGodson** [comment]
Looks like `align-items` and `justify-content` doesn't work either

**Comment by akamud** [comment]
Thanks for reporting! I'll release an update fixing this.

Any other rules missing?

**Comment by OscarGodson** [comment]
not that I found yet :)

**Comment by akamud** [comment]
I just released Can I Use version 0.5.3 which fixes this.

Based on [this](http://caniuse.com/#feat=flexbox), it will now work for all these properties: "flex-box", "flex-direction", "flex-wrap", "flex-flow", "flex-grow", "flex-basis", "display:flex" "flex", "inline-flex", "display:inline-flex", "align-content", "align-items", "align-self", "justify-content", "order".

Thanks again for using and reporting!
